version: "3.9"
services:
  de_psql:
    image: postgres:15
    container_name: de_psql
    volumes:
      - ./storage/postgres_data:/var/lib/postgresql/data
      - ./pg_hba.conf:/tmp/pg_hba.conf
      # - ./load_dataset:/tmp/load_dataset
    command: ["postgres", "-c", "hba_file=/tmp/pg_hba.conf"]
    ports:
       - "5432:5432"
    env_file: .env
    networks:
      - de_network
    
  # Dagster
  de_dagster:
    build:
      context: ./dagster/
      dockerfile: Dockerfile
    container_name: de_dagster
    image: de_dagster

  de_dagster_dagit:
    image: de_dagster:latest
    entrypoint:
      - dagit
      - -h
      - "0.0.0.0"
      - -p
      - "3001"
      - -w
      - workspace.yaml
      # - dagster
      # - dev 
      # - -h
      # - "0.0.0.0"
      # - -p 
      # - "3001"
    container_name: de_dagster_dagit
    expose:
      - "3001"
    ports:
      - "3001:3001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dagster_home:/opt/dagster/dagster_home
    env_file:
      - .env
    networks:
      - de_network

  de_dagster_daemon:
    image: de_dagster:latest
    entrypoint:
      - dagster-daemon
      - run
    container_name: de_dagster_daemon
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dagster_home:/opt/dagster/dagster_home
    env_file:
      - .env
    networks:
      - de_network

  etl_pipeline:
    build:
      context: ./etl_pipeline
      dockerfile: Dockerfile
    container_name: etl_pipeline
    image: etl_pipeline:latest
    user: root
    volumes:
      - ./etl_pipeline:/opt/dagster/app/etl_pipeline
      # - ./etl_pipeline/spark-defaults.conf:/usr/local/spark/conf/spark-defaults.conf
    env_file:
      - .env
    ports:
      - "4000:4000"
    networks:
      - de_network

networks:
  de_network:
    driver: bridge
    name: de_network